/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef MVERTUTIL_API
#define MVERTUTIL_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern MVERTUTIL_API FName MVERTUTIL_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class MVERTUTIL_API UVertUtil : public UObject
{
public:
    DECLARE_FUNCTION(execSetMeshRotation);
    DECLARE_FUNCTION(execGetMeshRotation);
    DECLARE_FUNCTION(execSetMeshOrigin);
    DECLARE_FUNCTION(execGetMeshOrigin);
    DECLARE_FUNCTION(execSetMeshSize);
    DECLARE_FUNCTION(execGetMeshSize);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execGetVertexLocationLOD);
    DECLARE_FUNCTION(execGetVertexLocation);
    DECLARE_CLASS(UVertUtil,UObject,0,MVertUtil)
    NO_DEFAULT_CONSTRUCTOR(UVertUtil)
};

#endif

AUTOGENERATE_FUNCTION(UVertUtil,-1,execSetMeshRotation);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetMeshRotation);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execSetMeshOrigin);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetMeshOrigin);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execSetMeshSize);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetMeshSize);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetVertexLocationLOD);
AUTOGENERATE_FUNCTION(UVertUtil,-1,execGetVertexLocation);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
